name: tezkor
version: 0.2.9+5
description: A powerful Flutter build CLI tool with automatic version management, smart file naming, and personalized experience
repository: https://github.com/ErkinjonYusupov/Tezkor-flutter-build-managaer-.git
homepage: https://github.com/ErkinjonYusupov/Tezkor-flutter-build-managaer-.git
environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  tezkor: tezkor

dependencies:
  args: ^2.4.2
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3


